### ISSUE TITLE
fts3；windows下essay.txt等

### ISSUE THREAD

**Issue by cryptogun** [osfans/rime-tool#1]
我也来帮衬啦。
- 1. Python 3.4.0（v3.4.0:04f714765c13）环境下，提示无fts3模型。google办法，替换最新版`C:\Python 34\DLLs\sqlite3.dll` 就好了。
- 2. Windows下八股文在`C:\\Program Files (x86)\\Rime\\weasel-0.9.30\\data\\` ，`trime-tool.py`得对这种情况处理一下。
- 3. dict里,  

``` python
use_preset_vocabulary: true  
max_phrase_length: 7  
```

则`trime.db`有40多M，怕会很卡。如果引入的八股文最大词长改成3，则有20多M。可能原因：为了覆盖地域更广，平均每个字的读音比较多，八股文自动编码的结果成倍增加。
继续跑去trime项目反馈一下。
- 4. 你的readme里，没提怎么处理`dict.yaml`，其实是不用人处理的。但没动手之前会一直有疑问：“`schema.yaml`输入了命令行，那`dict.yaml`要不要？”

**Comment by osfans** [comment]
多謝！收到！我整理到主頁說明中去。

**Comment by osfans** [comment]
是啊dict.yaml是自動找的。
essay.txt在brise目錄中也是有的。所以如果下載了brise子項目，就會找到了。
