### ISSUE TITLE
求教“去重工具：uniq.py”的使用法！

### ISSUE THREAD

**Issue by zaqzrh** [osfans/rime-tool#2]
謝謝。

**Comment by osfans** [comment]
這個要命令行的，而且會覆蓋原始文件。功能就是把後面出現重複行去掉，保留在它第一次出現的位置。

> python3 uniq.py 文件名。

**Comment by osfans** [comment]
也可以固定文件名，改成雙擊執行，比如自動給`input.txt`文件去重，只要添加如下一句：

``` diff
diff --git a/uniq.py b/uniq.py
index 3fc9e07..09a6fa9 100755
--- a/uniq.py
+++ b/uniq.py
@@ -1,6 +1,8 @@
 #!/usr/bin/env python3
 import sys

+sys.argv[1:] = ["input.txt"]
+
 if len(sys.argv) == 1:
   print("Usage: %s filename" % sys.argv[0])
   exit
```

**Comment by zaqzrh** [comment]
如地球拼音terra_pinyin.dict.yaml(.txt)有詞：
〇 ling2   23
〇 ling2
〇 ling2   544
才分  cai2 fen4
才分  cai2 fen4
；
我的批處理：
uniq.py terra_pinyin.dict.yaml或改(.txt)
或
python3 uniq.py terra_pinyin.dict.yaml或改(.txt)
沒有結果
？？

**Comment by osfans** [comment]
直接覆蓋源文件，應該會去掉第二個“才分 cai2 fen4”。

**Comment by zaqzrh** [comment]
如果「〇」不管，就去一个「才分 cai2 fen4」，那文本編輯器已很容易的呀，我常用cnbook「刪除重複行」

**Comment by osfans** [comment]
所以詞頻累加？

**Comment by osfans** [comment]
@zaqzrh  批處理的工具，處理一個目錄下的所有文件。另外像import_preset: default這些重複的行不會刪掉。

**Comment by zaqzrh** [comment]
@osfans 哦，幾個工具都更新了,不知在使用上又何變化？

**Comment by osfans** [comment]
功能沒變化，就是更規範點。
