### ISSUE TITLE
請求幫助寫一個分類匯總的程式

### ISSUE THREAD

**Issue by zaqzrh** [osfans/rime-tool#3]
百萬行數據，Excel分類匯總實在太慢了，
@osfans 大大有時間幫忙寫一個python3分類匯總的程式吧！感謝！

---

文檔內碼：GBK+UTF-8
文檔格式：字詞tab編碼
編碼格式：小狼毫格式(空格分隔)
編碼字符：字母、數字、拼音

---

好 hao
好 hao
工作  gong1 zuo4
工作  gong1 zuo4
工作  gong1 zuo4
樸 piáo
樸 piáo
樸 piáo
樸 piáo
這好像   zhè hǎo xiàng
這好像   zhè hǎo xiàng
這好像   zhè hǎo xiàng
這好像   zhè hǎo xiàng
這好像   zhè hǎo xiàng
這好像   zhè hǎo xiàng

---
## 分類匯總結果：字詞tab編碼tab數量

好 hao 2
工作  gong1 zuo4  3
樸 piáo   4
這好像   zhè hǎo xiàng    6

**Comment by osfans** [comment]
跟上次的詞頻統計工具差不多？

**Comment by osfans** [comment]
相當於默認詞頻是1吧？

**Comment by osfans** [comment]
改好了。改進了上次的freq_sum。而且兼容上次的格式。
第三列詞頻也可以加，不加默認就是1。

**Comment by zaqzrh** [comment]
谢谢！测试成功。
