### ISSUE TITLE
請求幫助寫一個篩選過濾的程式

### ISSUE THREAD

**Issue by zaqzrh** [osfans/rime-tool#4]
@osfans 幫忙寫一個python3篩選過濾的程式！

文檔內碼：GBK+UTF-8
文檔格式：字詞tab編碼
編碼格式：小狼毫格式(空格分隔)
編碼字符：字母、數字、拼音

---

好 hao
好 hao
工作 gong1 zuo4
工作 gong1 zuo4
工作 gong1 zuo4
樸 piáo
樸 piáo
樸 piáo
樸 piáo
這好像 zhè hǎo xiàng
這好像 zhè hǎo xiàng
這好像 zhè hǎo xiàng
這好像 zhè hǎo xiàng
這好像 zhè hǎo xiàng
這好像 zhè hǎo xiàng

---
## 篩選條件：

樸
工作

---
## 篩選結果：

工作 gong1 zuo4
工作 gong1 zuo4
工作 gong1 zuo4
樸 piáo
樸 piáo
樸 piáo
樸 piáo

**Comment by ghost** [comment]
我不懂 Python，不過你還可以用跨平臺的 SQLite3 數據庫管理工具處理這些數據。SQLite 的命令也不難學。

首先到  SQLite 官網下載目前的最新版 3.8.10.2：
https://www.sqlite.org/download.html
https://www.sqlite.org/2015/sqlite-shell-win32-x86-3081002.zip

然後把工具解壓到你的數據文件旁邊，再解壓出[我提供的批處理腳本](http://likelikeslike.qiniudn.com/data/github/SQLiteScripts.zip)就可以用了。已帶說明。

`sqlite3.exe` 本身也可以直接打開來用的。不過得先設定好字體（中文系統可無視）：
http://support.microsoft.com/kb/247815/en-us/
在打開 `sqlite3.exe` 後輸入該命令並執行，令 UTF-8 編碼的字符正確顯示：`.shell chcp 65001`

**Comment by zaqzrh** [comment]
@osfans @jakwings 對於非計算機專業的人，不用說寫代碼，看代碼也是一件很蛋痛的事。什麼高級語言C、B、P，就連批處理只會一點點，好在學了一些正則表達式。基本用cnbook和Excel能解決一些問題。但有時也不是那麼如意的。

**Comment by ghost** [comment]
@zaqzrh 我知道。我已經提供了解決這個問題的腳本了，也有解決你上一個問題的腳本；要你下載的工具也只是個單獨的 EXE 文件罷了，比 Python 輕便得多。

**Comment by zaqzrh** [comment]
SQLite3太慢了，跟Excel一樣慢，300萬行篩選50萬的詞，用了30分鐘只篩選20萬條，還是請求@osfans 有時間的時候幫忙寫一個python3篩選過濾的程式吧！先謝了！

**Comment by osfans** [comment]
好的，有時間幫你寫個。

**Comment by osfans** [comment]
條件怎麼搞？另外單獨的一個文件？

**Comment by ghost** [comment]
好吧，雖然在我這幾分鍾就搞定了。腳本還能優化的，你有需要再說吧。

**Comment by zaqzrh** [comment]
非常感謝二位的幫助！
@osfans 輸入input.txt，條件match.txt，輸出output.txt
@jakwings 這個SQLite3還可以優化？那有時間把它搞出來試試，也可以幫助一些人吧。
粵拼搞得不錯！！

**Comment by ghost** [comment]
把警告信息去掉就快很多了，一兩分鐘左右。再不行就看看說明給的優化提示吧。文件下載地址不變。

**Comment by osfans** [comment]
@jakwings sql用得這麼熟啊，我之前trime用的是sqlite的fts表格，那個超快，專爲搜索引擎優化的。估計幾秒鍾。

**Comment by osfans** [comment]
我這邊python的時間是3秒鐘：3百萬選50萬。等@zaqzrh 的測試時間。如果還是慢的話，可以從python裏使用sqlite3的fts表格看看。

**Comment by ghost** [comment]
@osfans 哈，最近一直搞碼表才去學的，其實不怎麼熟。這種小問題用 Python 的原生數據結構更快，大概十幾秒。我用 900 萬行數據測 60 萬詞條（一半是拖時間的），其實很多時間都耗在數據讀取上了。

才發現還有 [SQLite4](https://sqlite.org/src4/doc/trunk/www/design.wiki)，不知性能怎麼樣。

**Comment by osfans** [comment]
900 萬行數據測 60 萬詞條，用了7秒。
